-- MySQL Script generated by MySQL Workbench
-- Wed Jun 25 10:16:36 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Cinemacousas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Cinemacousas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Cinemacousas` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `Cinemacousas` ;

-- -----------------------------------------------------
-- Table `account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `account` ;

CREATE TABLE IF NOT EXISTS `account` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `modified_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `email_UNIQUE` ON `account` (`email` ASC) VISIBLE;

CREATE UNIQUE INDEX `username` ON `account` (`username` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `account_session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `account_session` ;

CREATE TABLE IF NOT EXISTS `account_session` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `account_id` INT NOT NULL,
  `session_token` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `expires_at` TIMESTAMP NULL DEFAULT NULL,
  `is_active` TINYINT(1) NULL DEFAULT '1',
  `ip_address` VARCHAR(45) NULL DEFAULT NULL,
  `user_agent` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `account_session_ibfk_1`
    FOREIGN KEY (`account_id`)
    REFERENCES `account` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 121
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `session_token` ON `account_session` (`session_token` ASC) VISIBLE;

CREATE INDEX `idx_session_token` ON `account_session` (`session_token` ASC) VISIBLE;

CREATE INDEX `idx_account_id` ON `account_session` (`account_id` ASC) VISIBLE;

CREATE INDEX `idx_expires_at` ON `account_session` (`expires_at` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `ageprice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ageprice` ;

CREATE TABLE IF NOT EXISTS `ageprice` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `agemax` INT NOT NULL,
  `agemin` INT NOT NULL,
  `factor` DECIMAL(4,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `movie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `movie` ;

CREATE TABLE IF NOT EXISTS `movie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `duration` INT NOT NULL,
  `director` VARCHAR(45) NOT NULL,
  `cast` VARCHAR(255) NOT NULL,
  `synopsis` VARCHAR(5000) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `room` ;

CREATE TABLE IF NOT EXISTS `room` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `nb_rows` INT NOT NULL,
  `nb_columns` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `showing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `showing` ;

CREATE TABLE IF NOT EXISTS `showing` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `starttime` TIME NOT NULL,
  `baseprice` INT NOT NULL,
  `room_id` INT NOT NULL,
  `movie_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_showing_movie1`
    FOREIGN KEY (`movie_id`)
    REFERENCES `movie` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_showing_room1`
    FOREIGN KEY (`room_id`)
    REFERENCES `room` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_seance_room1_idx` ON `showing` (`room_id` ASC) VISIBLE;

CREATE INDEX `fk_seance_movie1_idx` ON `showing` (`movie_id` ASC) VISIBLE;

CREATE INDEX `fk_seance_room1` ON `showing` (`room_id` ASC) VISIBLE;

CREATE INDEX `fk_seance_movie1` ON `showing` (`movie_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `booking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `booking` ;

CREATE TABLE IF NOT EXISTS `booking` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `price` DECIMAL(10,2) NULL DEFAULT NULL,
  `account_id` INT NOT NULL,
  `showing_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_booking_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `account` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_booking_showing1`
    FOREIGN KEY (`showing_id`)
    REFERENCES `showing` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_booking_account1_idx` ON `booking` (`account_id` ASC) VISIBLE;

CREATE INDEX `fk_booking_showing1_idx` ON `booking` (`showing_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `customer` ;

CREATE TABLE IF NOT EXISTS `customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(100) NOT NULL,
  `age` INT NOT NULL,
  `pmr` TINYINT NOT NULL DEFAULT '0',
  `booking_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_customer_booking1`
    FOREIGN KEY (`booking_id`)
    REFERENCES `booking` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_customer_booking1_idx` ON `customer` (`booking_id` ASC) VISIBLE;

CREATE INDEX `fk_customer_booking1` ON `customer` (`booking_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `seat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seat` ;

CREATE TABLE IF NOT EXISTS `seat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` ENUM('normal', 'pmr', 'stair', 'empty') NOT NULL DEFAULT 'normal',
  `room_id` INT NOT NULL,
  `seat_row` CHAR(1) NOT NULL,
  `seat_column` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_seat_room1`
    FOREIGN KEY (`room_id`)
    REFERENCES `room` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 133
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `unique_seat_per_room` ON `seat` (`room_id` ASC, `seat_row` ASC, `seat_column` ASC) VISIBLE;

CREATE INDEX `fk_seat_room1_idx` ON `seat` (`room_id` ASC) VISIBLE;

CREATE INDEX `fk_seat_room1` ON `seat` (`room_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `seatreservation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `seatreservation` ;

CREATE TABLE IF NOT EXISTS `seatreservation` (
  `customer_id` INT NOT NULL,
  `showing_id` INT NOT NULL,
  `seat_id` INT NOT NULL,
  PRIMARY KEY (`showing_id`, `seat_id`),
  CONSTRAINT `fk_reservation_seat1`
    FOREIGN KEY (`seat_id`)
    REFERENCES `seat` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_seatreservation_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `customer` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_seatreservation_showing1`
    FOREIGN KEY (`showing_id`)
    REFERENCES `showing` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_seatreservation_customer1_idx` ON `seatreservation` (`customer_id` ASC) VISIBLE;

CREATE INDEX `fk_seatreservation_showing1_idx` ON `seatreservation` (`showing_id` ASC) VISIBLE;

CREATE INDEX `fk_reservation_seat1_idx` ON `seatreservation` (`seat_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
